services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${POSTGRES_USER}
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 30s
      retries: 5
      interval: 1m30s

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=shop"
    env_file:
      - path: ./.env
        required: true
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - php

volumes:
  data: